name: Update Daily Devotion

on:
  schedule:
    - cron: '2 7 * * *'      # Runs every day at 07:02 UTC (adjust as needed)
  workflow_dispatch:         # Allows you to trigger manually if desired

jobs:
  update-devotion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Update devotions.json
        run: |
          node .github/scripts/updateDevotion.js

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add public/devotions.json
          git commit -m "Auto-update devotions.json for today" || echo "No changes to commit"
          git push

