name: Update Daily Devotion

on:
  schedule:
    - cron: '2 7 * * *'
  workflow_dispatch:

jobs:
  update-devotion:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # This is crucial!

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install luxon

      - name: Run daily devotion update (Python)
        run: python3 update_daily_devotion.py

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name 'JimGram'
          git config --global user.email 'jimgram@gmail.com'
          git add public/devotions.json
          git commit -m "Auto-update devotions.json for today" || echo "No changes to commit"
          git push https://x-access-token:${GH_PAT}@github.com/DailyLectio/calm.git HEAD:main