name: Daily Devotions Publish

on:
  schedule:
    - cron: '0 7 * * *'    # Runs daily at 07:00 UTC
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PERP_KEY: ${{ secrets.PERPLEXITY_API_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch full exegesis report
        id: full
        run: |
          curl -s -X POST \
            https://api.perplexity.ai/tasks/YOUR_FULL_TASK_ID/run \
            -H "Authorization: Bearer $PERP_KEY" \
            -H "Content-Type: application/json" \
            -d '{}' \
            -o full.json

      - name: Extract JSON synopsis
        id: dev
        run: |
          FULL=$(jq -r .reportText < full.json)
          curl -s -X POST \
            https://api.perplexity.ai/tasks/YOUR_SYNOPSIS_TASK_ID/run \
            -H "Authorization: Bearer $PERP_KEY" \
            -H "Content-Type: application/json" \
            -d "{\"input_text\":$(jq -Rs . <<< \"$FULL\")}" \
            -o dev.json

      - name: Validate and write public/devotions.json
        run: |
          # Basic JSON syntax check
          jq . < dev.json > public/devotions.json

      - name: Commit & push updated JSON
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/devotions.json
          git commit -m "Daily devotion update: $(date +%F)" || echo "No changes to commit"
          git push

      - name: Archive full exegesis report
        run: |
          mkdir -p archive
          cp full.json archive/$(date +%F)-full.json