name: Update Daily Devotion

on:
  # Run this immediately after the weekly workflow finishes successfully
  workflow_run:
    workflows: ["Generate Weekly Devotions (Fri–Thu)"]
    types: [completed]

  # Still allow manual triggers
  workflow_dispatch:

concurrency:
  group: daily-devotion-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-devotion:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      APP_TZ: America/New_York

    steps:
      - name: Checkout repo (main, full history)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Only needed if your update script imports third-party libs (it doesn't now)
      # Safe to leave; it’s quick. Remove if truly stdlib-only.
      - name: Install deps (fast)
        run: |
          python -m pip install --upgrade pip
          pip install --no-input requests jsonschema openai || true

      # Fail fast if today is not found in weeklyfeed.json
      - name: Sanity check weeklyfeed for today
        env:
          APP_TZ: America/New_York
        run: |
          python - <<'PY'
          import json, os, sys
          from datetime import datetime
          try:
              from zoneinfo import ZoneInfo
          except Exception:
              ZoneInfo = None
          tz = os.environ.get("APP_TZ","UTC")
          today = (datetime.now(ZoneInfo(tz)).date().isoformat()
                   if ZoneInfo else datetime.utcnow().date().isoformat())
          with open("public/weeklyfeed.json","r",encoding="utf-8") as f:
              data = json.load(f)
          ok = any(isinstance(e,dict) and str(e.get("date","")).strip()==today for e in data)
          print("tz=", tz, "today=", today, "found=", ok)
          sys.exit(0 if ok else 1)
          PY

      - name: Run daily devotion update
        env:
          APP_TZ: America/New_York
        run: |
          set -euo pipefail
          python update_daily_devotion.py --tz "$APP_TZ"

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -euo pipefail
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          # Stage only files that actually exist
          test -f public/devotions.json && git add public/devotions.json || true
          test -f dist/devotions.json && git add dist/devotions.json || true
          # Archive updates (index + per-day files) if your script wrote them
          git add public/past_reflections || true

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily devotion update for $(date -u +%Y-%m-%d)"
            git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
          fi
