name: Update Daily Devotion

on:
  # Fire automatically when the weekly job finishes successfully
  workflow_run:
    workflows: ["Generate Weekly Devotions (Fri–Thu)"]
    types: [completed]

  # Safety net: also run every day around 3:35am Eastern
  # (EST=UTC-5 → 08:35; EDT=UTC-4 → 07:35)
  schedule:
    - cron: "35 8 * * *"   # ~03:35 EST
    - cron: "35 7 * * *"   # ~03:35 EDT

  # Manual button in Actions
  workflow_dispatch: {}

concurrency:
  group: daily-devotion
  cancel-in-progress: true

jobs:
  update-devotion:
    # If triggered by weekly, only proceed on success
    if: >
      github.event_name != 'workflow_run' ||
      (github.event.workflow_run.conclusion == 'success')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      APP_TZ: America/New_York

    steps:
      - name: Checkout repo (main, full history)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Fail fast if today's date isn't in weeklyfeed.json
      - name: Sanity check weeklyfeed for today
        run: |
          python3 - <<'PY'
          import json, os, sys
          from datetime import datetime
          from zoneinfo import ZoneInfo
          tz = os.environ.get("APP_TZ","America/New_York")
          today = datetime.now(ZoneInfo(tz)).date().isoformat()
          try:
            data = json.load(open("public/weeklyfeed.json", "r", encoding="utf-8"))
          except Exception as e:
            print("[error] weeklyfeed.json missing or unreadable:", e)
            sys.exit(1)
          found = any(str(e.get("date","")).strip()==today for e in data if isinstance(e,dict))
          print("tz=", tz, "today=", today, "found=", found)
          sys.exit(0 if found else 1)
          PY

      - name: "Optional - log saint.json availability (non-fatal)"
        run: |
          echo "Checking saint.json…"
          set -e
          curl -I https://dailylectio.org/saint.json || true
          curl -fsSL https://dailylectio.org/saint.json | head -c 400 || echo "saint.json not available (skipping override)"
          echo 

      - name: Run daily devotion update (Python)
        run: |
          python3 update_daily_devotion.py --tz "$APP_TZ" --skip-dist

      - name: Commit and push changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -euo pipefail
          git config --local user.name  "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # If dist/ is ignored in .gitignore, -f forces add safely.
          git add public/devotions.json public/past_reflections/ public/past_reflections/index.json
          git add -f dist/devotions.json || true
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Daily devotion update for $(TZ=$APP_TZ date +%Y-%m-%d)"
          git push https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git HEAD:main
