name: Generate Weekly Devotions (Fri–Thu)

on:
  schedule:
    # 3:00am local NY time (handles DST by providing both)
    - cron: "0 8 * * 2"   # 03:00 EST (UTC-5)
    - cron: "0 7 * * 2"   # 03:00 EDT (UTC-4)
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date (YYYY-MM-DD). Blank = script default"
        required: false
        default: ""
      days:
        description: "How many days (default 7)"
        required: false
        default: "7"

jobs:
  gen-weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_PROJECT: ${{ secrets.OPENAI_PROJECT }}
      GH_PAT: ${{ secrets.GH_PAT }}
      APP_TZ: America/New_York
      GEN_MODEL: gpt-4o-mini
      GEN_FALLBACK: gpt-4o-mini
      GEN_TEMP: "0.60"
      GEN_TEMP_REPAIR: "0.55"
      GEN_TEMP_QUOTE: "0.35"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests jsonschema openai

      - name: Sanity check OpenAI env
        run: |
          python - <<'PY'
          import os
          print("Has OPENAI_API_KEY?", bool(os.getenv("OPENAI_API_KEY")))
          print("Has OPENAI_PROJECT?", bool(os.getenv("OPENAI_PROJECT")))
          PY

      - name: Show existing weeklyfeed.json (if present)
        run: |
          if [ -f public/weeklyfeed.json ]; then
            echo "SHA: $GITHUB_SHA"
            head -n 60 public/weeklyfeed.json
          else
            echo "No existing public/weeklyfeed.json (first run?)"
          fi

      - name: USCCB precheck (no OpenAI calls)
        run: |
          echo "[info] tz=$APP_TZ start=${{ github.event.inputs.start_date || '' }} days=${{ github.event.inputs.days || '7' }} model=$GEN_MODEL"
          USCCB_PRECHECK=1 START_DATE="${{ github.event.inputs.start_date }}" DAYS="${{ github.event.inputs.days }}" \
          python scripts/generate_weekly.py

      - name: Generate weeklyfeed.json
        env:
          TZ: America/New_York
        run: |
          set -euo pipefail
          export START_DATE="${{ github.event.inputs.start_date }}"
          export DAYS="${{ github.event.inputs.days }}"
          python scripts/generate_weekly.py

      - name: Generate saints weeklydevotion.json (CSV-first)
        shell: bash
        run: |
          set -euo pipefail
          # Use the dispatch input when provided; otherwise read first date from the built weeklyfeed.json
          START="${{ github.event.inputs.start_date }}"
          if [ -z "$START" ]; then
            START="$(jq -r '.[0].date' public/weeklyfeed.json)"
          fi
          echo "[saints] start=$START"

          # Derive YEAR and YYYY-MM to select the monthly authority CSV
          YEAR="$(date -d "$START" +%Y)"
          YM="$(date -d "$START" +%Y-%m)"

          python -m scripts.generate_saints_weekly             --start "$START"             --authority "data/saints/${YEAR}/saints_authority_${YM}.csv"             --out public/weeklydevotion.json

      - name: Merge saints into weeklyfeed.json
        shell: bash
        run: |
          set -euo pipefail
          python scripts/merge_saints_into_weeklyfeed.py             --weekly public/weeklyfeed.json             --saints public/weeklydevotion.json             --out public/weeklyfeed.json



            - name: Generate saints weeklydevotion.json (CSV-first)
        shell: bash
        run: |
          set -euo pipefail
          # START comes from dispatch input; if blank, take first date from the built weeklyfeed
          START="${{ github.event.inputs.start_date }}"
          if [ -z "$START" ]; then
            START="$(jq -r '.[0].date' public/weeklyfeed.json)"
          fi

          # Derive YEAR and YYYY-MM for the authority CSV path
          YEAR="$(date -d "$START" +%Y)"
          YM="$(date -d "$START" +%Y-%m)"

          python -m scripts.generate_saints_weekly \
            --start "$START" \
            --authority "data/saints/${YEAR}/saints_authority_${YM}.csv" \
            --out public/weeklydevotion.json

      - name: Merge saints into weeklyfeed.json
        shell: bash
        run: |
          set -euo pipefail
          python scripts/merge_saints_into_weeklyfeed.py \
            --weekly public/weeklyfeed.json \
            --saints public/weeklydevotion.json \
            --out public/weeklyfeed.json

      - name: Validate weeklyfeed.json shape & fields
        run: |
          set -euo pipefail
          test -f public/weeklyfeed.json
          jq 'length==7' public/weeklyfeed.json >/dev/null
          jq -e 'all(.[]; has("date") and has("quote") and has("quoteCitation") and has("firstReading") and has("psalmSummary") and has("gospelSummary") and has("saintReflection") and has("dailyPrayer") and has("theologicalSynthesis") and has("exegesis") and has("secondReading") and has("tags") and has("usccbLink") and has("cycle") and has("weekdayCycle") and has("feast") and has("gospelReference") and has("firstReadingRef") and has("secondReadingRef") and has("psalmRef") and has("gospelRef") and has("lectionaryKey"))' public/weeklyfeed.json >/dev/null
          jq -e 'all(.[]; (.cycle|tostring|startswith("Year ")) and (.weekdayCycle|tostring|startswith("Cycle ")))' public/weeklyfeed.json >/dev/null
          jq -e 'all(.[]; (.secondReading|type=="string") and (.feast|type=="string") and (.secondReadingRef|type=="string"))' public/weeklyfeed.json >/dev/null

      # ✅ Commit first, then rebase+push (fixes “cannot pull with rebase: unstaged changes”)
      - name: Commit and push weeklyfeed.json (safe)
        shell: bash
        run: |
          set -euo pipefail

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage only the generated file
          git add public/weeklyfeed.json

          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "chore: weeklyfeed update (auto)"

          # Rebase on latest remote and push our commit
          git fetch origin main
          git -c rebase.autoStash=true pull --rebase origin main
          git push origin HEAD:main
