name: Generate Weekly Devotions

on:
  schedule:
    - cron: '5 8 * * 4'   # Thursdays 08:05 UTC (≈ 4:05am ET in summer, 3:05am ET in winter)
  workflow_dispatch:
    inputs:
      start_date:
        description: "Start date (YYYY-MM-DD). Leave blank for today."
        required: false
        default: ""
      days:
        description: "How many days to generate"
        required: false
        default: "7"

jobs:
  gen-weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      APP_TZ: America/New_York
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      START_DATE: ""   # optional override; empty = today
      DAYS: "7"        # generate N days (today..today+N-1)
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install openai jsonschema

      - name: Show weeklyfeed.json header
        run: |
          echo "SHA: $GITHUB_SHA"
          head -n 60 public/weeklyfeed.json

      - name: Sanity check enums
        run: |
          python - <<'PY'
          import json,sys
          d=json.load(open("public/weeklyfeed.json","r",encoding="utf-8"))
          if not isinstance(d, list):
              print("weeklyfeed.json is not a top-level array"); sys.exit(1)
          bad=[(i+1,x.get("date"),x.get("cycle"),x.get("weekdayCycle")) for i,x in enumerate(d)
               if not str(x.get("cycle","")).startswith("Year ")
               or not str(x.get("weekdayCycle","")).startswith("Cycle ")]
          if bad:
              print("Bad enum rows (first 5):", bad[:5])
              sys.exit(1)
          print("Enums look good.")
          PY

      - name: Generate weeklyfeed.json
        run: |
          python scripts/generate_weekly.py
      - name: Commit and push weeklyfeed.json
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add public/weeklyfeed.json
          git diff --staged --quiet || git commit -m "Weeklyfeed refresh"
          git push
