name: Update Devotions via Perplexity API

on:
  schedule:
    - cron: '0 7 * * *'  # daily at 07:00 UTC
  workflow_dispatch:

env:
  PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
  TASK_1_ID:          ${{ secrets.TASK_1_ID }}
  TASK_2_ID:          ${{ secrets.TASK_2_ID }}
  TASK_3_ID:          ${{ secrets.TASK_3_ID }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch raw exegesis (Task 1)
        run: |
          curl -s -X POST "https://api.perplexity.ai/tasks/${TASK_1_ID}/run" \
            -H "Authorization: Bearer ${PERPLEXITY_API_KEY}" \
            -H "Content-Type: application/json" \
            -o task1_raw.json

      - name: Write raw text to file
        run: |
          jq -r .reportText task1_raw.json > raw_exegesis.txt

      - name: Generate full JSON (Task 2)
        run: |
          TEXT=$(jq -Rs . < raw_exegesis.txt)
          curl -s -X POST "https://api.perplexity.ai/tasks/${TASK_2_ID}/run" \
            -H "Authorization: Bearer ${PERPLEXITY_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"input_text\":$TEXT}" \
            -o devotions-full.json

      - name: Generate summary JSON (Task 3)
        run: |
          TEXT=$(jq -Rs . < raw_exegesis.txt)
          curl -s -X POST "https://api.perplexity.ai/tasks/${TASK_3_ID}/run" \
            -H "Authorization: Bearer ${PERPLEXITY_API_KEY}" \
            -H "Content-Type: application/json" \
            -d "{\"input_text\":$TEXT}" \
            -o devotions.json

      - name: Publish JSON files
        run: |
          mkdir -p public
          mv devotions-full.json public/devotions-full.json
          mv devotions.json      public/devotions.json

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install validation tools
        run: |
          pip install jsonschema jq

      - name: Validate JSONs
        run: |
          python - << 'EOF'
import json, pathlib, sys
from jsonschema import validate, ValidationError

schema = json.loads(pathlib.Path("schemas/devotion.schema.json").read_text())

for fname in ["public/devotions.json", "public/devotions-full.json"]:
    path = pathlib.Path(fname)
    if not path.exists() or path.stat().st_size == 0:
        print(f"{fname} is missing or empty; skipping validation.")
        continue

    data = json.loads(path.read_text())
    try:
        validate(instance=data, schema=schema)
        print(f"{fname} is valid")
    except ValidationError as e:
        print(f"{fname} invalid:", e.message)
        sys.exit(1)
EOF

      - name: Archive and commit
        run: |
          today=$(date -u +%F)
          mkdir -p archive/public/daily/$today
          cp public/devotions.json        archive/public/daily/$today/
          cp public/devotions-full.json   archive/public/daily/$today/

          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/devotions*.json archive/public/daily/$today/*

          if ! git diff --cached --quiet; then
            git commit -m "Daily devotions: $today"
            git push
          else
            echo "No changes to commit."
          fi
