name: Update Devotions via Perplexity API

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

env:
  PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
  MODEL: sonar
  MAX_TOKENS: 1500
  TRIM_CHARS: 4000

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Fetch raw exegesis (Task 1)
        run: |
          cat > user1.txt << 'EOF'
          Provide a daily exegesis of the Roman Catholic readings, psalms, and saint of the day; begin with a single summary quote with citation (e.g. Gn 1:15), followed by a theological summary of the day's reflections and applications, then a 3–5 sentence summary of each category (first readings, psalm, gospel, saint). After that, include a section titled "Detailed Scriptural Exegesis:" and write an in-depth, paragraph-length exegesis of the passages with historical context. End with an original summary prayer encompassing the day's overarching spiritual messages.
          EOF
          jq -n \
            --arg model "$MODEL" \
            --rawfile content user1.txt \
            --argjson max_tokens "${MAX_TOKENS:-1500}" \
            --argjson temperature 0.2 \
            --argjson search_domain_filter '["wikipedia.org","bible.usccb.org","catholicculture.org","-reddit.com"]' \
            --arg search_recency "week" \
            '{
              model: $model,
              messages: [{role:"user", content: $content}],
              max_tokens: $max_tokens,
              temperature: $temperature,
              search_domain_filter: $search_domain_filter,
              search_recency_filter: $search_recency
            }' \
          | jq . > payload1.json
          curl -s https://api.perplexity.ai/chat/completions \
            -H "Authorization: Bearer ${PERPLEXITY_API_KEY}" \
            -H "Content-Type: application/json" \
            -d @payload1.json \
            -o task1_raw.json

      - name: Extract raw text (trimmed)
        run: |
          jq -r '.choices[0].message.content' task1_raw.json > raw_exegesis.txt
          head -c ${TRIM_CHARS} raw_exegesis.txt > raw_trimmed.txt

      - name: Debug trimmed raw text
        run: |
          echo "=== raw_trimmed.txt ==="
          if [[ -s raw_trimmed.txt ]]; then
            head -n 20 raw_trimmed.txt
          else
            echo "(raw_trimmed.txt is empty)"
          fi

      - name: Detailed Exegesis (Task 2)
        run: |
          mkdir -p public
          jq -n \
            --arg model "$MODEL" \
            --rawfile text raw_trimmed.txt \
            --arg prompt "Extract the section starting with \"Detailed Scriptural Exegesis:\" and everything after it as a JSON object with key \"exegesis\"." \
            --argjson max_tokens "${MAX_TOKENS:-1500}" \
            --argjson temperature 0.2 \
            '{
              model: $model,
              messages:[{role:"user", content: ($prompt + "\n\n" + $text)}],
              max_tokens: $max_tokens,
              temperature: $temperature
            }' > payload2.json
          curl -s https://api.perplexity.ai/chat/completions \
            -H "Authorization: Bearer ${PERPLEXITY_API_KEY}" \
            -H "Content-Type: application/json" \
            -d @payload2.json \
            -o resp2.json

      - name: Debug resp2.json
        run: |
          echo "=== resp2.json ==="
          jq . resp2.json || cat resp2.json

      - name: Debug raw exegesis JSON
        run: |
          echo "=== resp2.json choices[0].message.content ==="
          jq -r '.choices[0].message.content' resp2.json | head -20

      - name: Build public/devotions-full.json
        run: |
          jq -r '.choices[0].message.content' resp2.json \
            | grep -v '^```
            | jq . \
            | jq -s '.' \
            > public/devotions-full.json

      - name: Feed JSON (Task 3)
        run: |
          mkdir -p public
          jq -n \
            --arg model "$MODEL" \
            --rawfile text raw_trimmed.txt \
            --arg prompt "Extract these fields in this order as a JSON object: date (YYYY-MM-DD), quote, quoteCitation, firstReading, secondReading, psalmSummary, gospelSummary, dailyPrayer, saintReflection, theologicalSynthesis, tags, usccbLink, cycle, weekdayCycle, feast, gospelReference, gospelRef, firstReadingRef, secondReadingRef, psalmRef, lectionaryKey. Return one well-formed JSON object." \
            --argjson max_tokens "${MAX_TOKENS:-1500}" \
            --argjson temperature 0.2 \
            '{
              model: $model,
              messages:[{
                role:"user",
                content: ($prompt + "\n\n" + $text)
              }],
              max_tokens: $max_tokens,
              temperature: $temperature
            }' > payload3.json

          curl -s https://api.perplexity.ai/chat/completions \
            -H "Authorization: Bearer ${PERPLEXITY_API_KEY}" \
            -H "Content-Type: application/json" \
            -d @payload3.json \
            -o resp3.json

      - name: Debug resp3.json
        run: |
          echo "=== resp3.json ==="
          jq . resp3.json || cat resp3.json

      - name: Debug raw summary content
        run: |
          echo "=== resp3.json choices.message.content ==="
          jq -r '.choices.message.content' resp3.json | head -20

      - name: Build public/devotions.json
        run: |
          jq -r '.choices.message.content' resp3.json \
            | grep -v '^```' \
            | jq . \
            > public/devotions.json

      - name: Publish JSON files
        run: |
          ls -l public

      - name: Debug JSON
        run: |
          echo "=== public/devotions.json ==="
          cat public/devotions.json || echo "(missing)"
          echo
          echo "=== public/devotions-full.json ==="
          cat public/devotions-full.json || echo "(missing)"

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install jsonschema

      - name: Run JSON validation
        run: ./scripts/validate_devotions_advanced.py

      - name: Archive and commit devotions data
        run: |
          set -e
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          today=$(date -u +%F)
          mkdir -p archive/public/daily/$today
          cp public/devotions*.json archive/public/daily/$today/ || true
          git add public/devotions*.json archive/public/daily/$today/*
          if ! git diff --cached --quiet; then
            git commit -m "Daily devotions: $today"
            git push
          else
            echo "No changes to commit."
          fi
