name: Validate Devotions JSON

on:
  push:
    paths:
      - 'public/devotions.json'
      - 'schemas/devotion.schema.json'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install jq jsonschema

      - name: Snapshot — show key values from first array element
        run: |
          if [ ! -s public/devotions.json ]; then
            echo "No public/devotions.json to snapshot; exiting."
            exit 0
          fi
          echo "date\tcycle\tweekdayCycle"
          jq -r '.[0] | "\(.date)\t\(.cycle)\t\(.weekdayCycle)"' public/devotions.json

      - name: Validate JSON against schema
        run: |
          if [ ! -s public/devotions.json ]; then
            echo "public/devotions.json is missing or empty; skipping validation."
            exit 0
          fi
          pip install jsonschema
          cat > validate.py << 'EOF'
import json
import pathlib
import sys
from jsonschema import validate, ValidationError

schema = json.loads(pathlib.Path('schemas/devotion.schema.json').read_text())

try:
    data = json.loads(pathlib.Path('public/devotions.json').read_text())
except Exception as e:
    print("Failed to load JSON:", e)
    sys.exit(1)

try:
    validate(instance=data, schema=schema)
    print("public/devotions.json is valid")
except ValidationError as e:
    print("Validation error:", e.message)
    sys.exit(1)
EOF

          python3 validate.py