name: Validate Devotions JSON

on:
  push:
    paths:
      - 'public/devotions.json'
      - 'public/devotions-full.json'
      - 'schemas/devotion.schema.json'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install jq jsonschema

      - name: Snapshot — show key values from single object
        run: |
          echo "date\tcycle\tweekdayCycle"
          jq -r '"\(.date)\t\(.cycle)\t\(.weekdayCycle)"' public/devotions.json

      - name: Validate JSON against schema
        run: |
          python - <<PY
          import json, pathlib, sys
          from jsonschema import validate, ValidationError
          schema = json.loads(pathlib.Path('schemas/devotion.schema.json').read_text())
          errors = False
          for file in ["public/devotions.json"]:
              data = json.loads(pathlib.Path(f).read_text())
              try:
                  validate(instance=data, schema=schema)
                  print(f"{f}: valid")
              except ValidationError as e:
                  print(f"{f}: validation error: {e.message}")
                  errors = True
          if errors:
              sys.exit(1)
          PY