name: Validate Devotions JSON

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'public/**/*.json'
      - 'schemas/**/*.json'
      - 'scripts/validate_devotions.py'
  push:
    branches: [ main ]
    paths:
      - 'public/**/*.json'
      - 'schemas/**/*.json'
      - 'scripts/**/*.py'
  workflow_dispatch: {}   # lets you run it manually

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # ✅ IMPORTANT: checkout the PR HEAD, not the merge ref
      - name: Checkout PR HEAD
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Install validator deps
        run: |
          python -V
          pip install -q jsonschema jq

      # 👇 print exactly what the runner is validating
      - name: Debug — echo JSON snapshot
        run: |
          echo "HEAD SHA: $GITHUB_SHA"
          echo "First 11 weekly rows:"
          jq -r 'to_entries[] | select(.key<11) | "\(.key)\t\(.value.date)\tcycle=\(.value.cycle)\tweekdayCycle=\(.value.weekdayCycle)"' public/weeklyfeed.json
          echo "Search for bad strings:"
          LC_ALL=C grep -nE "Year[[:space:]]*C|Cycle[[:space:]]*I" public/weeklyfeed.json || echo "no matches"
          echo "Devotions object:"
          jq '{date, cycle, weekdayCycle}' public/devotions.json

      - name: Validate JSON files
        run: python scripts/validate_devotions.py