jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quick snapshot so you can see the first few rows in the logs
      - name: Debug — echo first 10 devotions
        run: |
          set -euo pipefail
          jq -r '
            .[0:10] |
            .[] | [.date, .cycle, .weekdayCycle] | @tsv
          ' public/devotions.json

      # 1) JSON must be an array
      - name: Assert devotions.json is an array
        run: |
          test "$(jq -r 'type' public/devotions.json)" = "array"

      # 2) Every item must have a valid YYYY-MM-DD date
      - name: Validate dates
        run: |
          set -euo pipefail
          # list any bad dates (if any)
          BAD="$(jq -r '.[].date' public/devotions.json | grep -vE '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' || true)"
          if [ -n "$BAD" ]; then
            echo "Invalid date strings found:"
            echo "$BAD"
            exit 1
          fi

      # 3) No duplicate dates
      - name: Check duplicate dates
        run: |
          set -euo pipefail
          DUPS="$(jq -r '.[].date' public/devotions.json | sort | uniq -d)"
          if [ -n "$DUPS" ]; then
            echo "Duplicate dates:"
            echo "$DUPS"
            exit 1
          fi

      # 4) Basic required keys present (adjust as you need)
      - name: Required keys exist
        run: |
          set -euo pipefail
          jq -e '
            all(.[]; 
              has("date") and
              has("quote") and
              has("quoteCitation") and
              has("firstReading") and
              has("psalmSummary") and
              has("gospelSummary") and
              has("saintReflection") and
              has("dailyPrayer") and
              has("theologicalSynthesis") and
              has("exegesis") and
              has("tags") and
              has("usccbLink") and
              has("cycle") and
              has("weekdayCycle") and
              has("feast") and
              has("gospelReference") and
              has("firstReadingRef") and
              has("psalmRef") and
              has("gospelRef") and
              has("lectionaryKey")
            )
          ' public/devotions.json >/dev/null