name: Validate Devotions JSON

on:
  push:
    paths:
      - 'public/devotions.json'
      - 'public/devotions-full.json'
      - 'schemas/devotion.schema.json'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install jsonschema

      - name: Validate JSON files
        run: |
          python - <<PY
          import json, pathlib, sys
          from jsonschema import validate, ValidationError
          schema = json.loads(pathlib.Path('schemas/devotion.schema.json').read_text())
          errors = False
          for f in ['public/devotions.json', 'public/devotions-full.json']:
              try:
                  data = json.loads(pathlib.Path(f).read_text())
                  validate(instance=data, schema=schema)
                  print(f"{f} is valid")
              except ValidationError as e:
                  print(f"Validation failed for {f}: {e.message}")
                  errors = True
          if errors:
              sys.exit(1)
          PY